### PR TITLE
Avoid deprecated import via collections.abc.Mapping

### LINKED ISSUE #129: No support for Python 3.10
The library cannot be used in Python 3.10

Here's the error when trying to run `train` in a SageMaker training image:

```
Traceback (most recent call last):
  File "/opt/venv/bin/train", line 5, in <module>
    from sagemaker_training.cli.train import main
  File "/opt/venv/lib/python3.10/site-packages/sagemaker_training/cli/train.py", line 14, in <module>
    from sagemaker_training import trainer
  File "/opt/venv/lib/python3.10/site-packages/sagemaker_training/trainer.py", line 23, in <module>
    from sagemaker_training import (
  File "/opt/venv/lib/python3.10/site-packages/sagemaker_training/entry_point.py", line 24, in <module>
    from sagemaker_training import _entry_point_type, environment, files, modules, runner
  File "/opt/venv/lib/python3.10/site-packages/sagemaker_training/environment.py", line 32, in <module>
    from sagemaker_training import logging_config, mapping, params
  File "/opt/venv/lib/python3.10/site-packages/sagemaker_training/mapping.py", line 155, in <module>
    class MappingMixin(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

The offending import gave a warning in Python 3.9

```
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
>>> import collections
>>> collections.Mapping
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
<class 'collections.abc.Mapping'>
```

but is an error in Python 3.10

```
Python 3.10.4 (main, Apr  2 2022, 09:04:19)
>>> import collections
>>> collections.Mapping
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'collections' has no attribute 'Mapping'
```

https://github.com/aws/sagemaker-training-toolkit/blob/v4.1.2/src/sagemaker_training/mapping.py#L155

### PR DESCRIPTION
**Pull request by lorenzwalthert**
*Issue #, if available:*

Partly fixes #129 by removing most obvious problem (my training script ran afterwards, but this is no guarantee).

*Description of changes:*

Since Python 3.3 (over 10 years ago), the following is deprecated: `from collections import Mapping`. In Python 3.9: 
```
<stdin>:1: DeprecationWarning: Using or importing the ABCs
  from 'collections' instead of from 'collections.abc' is deprecated
  since Python 3.3, and in 3.10 it will stop working
```

This PR replaces the offending statement as advised in the warning message.

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-training-toolkit/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-training-toolkit/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have used the regional endpoint when creating S3 and/or STS clients (if appropriate)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-training-toolkit/blob/master/README.md)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
@vishwakaria can you please have a look? This fixes a 10 (!) year old depreciation warning.

**Comment by vishwakaria** [comment]
> @vishwakaria can you please have a look? This fixes a 10 (!) year old depreciation warning and is a trivial change.

Adding package owner Satish to review.

**Comment by satishpasumarthi** [comment]
Addressed this in https://github.com/aws/sagemaker-training-toolkit/pull/156

**Comment by lorenzwalthert** [comment]
Thanks @satishpasumarthi. I do understand that it's sometimes easier to fix things yourself, but in general I feel like AWS could try to adhere a bit more to open-source culture and try to let people also commit to their repos 🙃

**Comment by satishpasumarthi** [comment]
Hi @lorenzwalthert , We are in the process of adding extra layer of security when the PR contributions are coming from away contributors. As of now, we are in the middle of the transition. We will be opening up the PR contributions from non-aws contributors very soon. sorry for any inconvenience.

**Pull request closed without merging**
