### PR TITLE
add general exception to filter

### PR DESCRIPTION
**Pull request by roywei**
Right now the sagemaker training toolkit only log error messages if we found certain error keyword in the logs.
We are missing general exception in the filter to log error messages. 
This PR adds that, right now we are filtering (general python exceptions, MPI errors, SageMaker library specific errors).

In future, we should extend this to custom exceptions and low level/C++ exceptions.

### CODE REVIEW

**Comment by satishpasumarthi** [comment]
Hi @roywei , Thanks for your PR. Could you please update the commit message to have a valid prefix as per https://github.com/aws/sagemaker-training-toolkit/blob/master/CONTRIBUTING.md#committing-your-change ? Otherwise, the changes look fine.

**Comment by roywei** [comment]
Thanks @satishpasumarthi ! updated commit message

**Review by satishpasumarthi — APPROVED** [review]
LGTM !

**Review by yl-to — APPROVED** [review]
LGTM.

**Pull request merged**
