### PR TITLE
feature: smdataparallel custom mpi options support

### PR DESCRIPTION
**Pull request by karan6181**
*Description of changes:*
- Support of custom MPI options for Sagemaker Distibuted Data Parallel. This feature will enable the user to pass the custom MPI flags during the training.

E.g.:
```
mpi_options = '-verbose -x NCCL_DEBUG=INFO'
distribution = {'smdistributed':{'dataparallel':{
                                    'enabled': True,
                                    'custom_mpi_options': mpi_options,
                                    }
                                }
                }
```
**NOTE**
The SageMaker Distributed Data Parallel cutom MPI support require changes in [sagemaker-training-toolkit](https://github.com/aws/sagemaker-training-toolkit) and [sagemaker-python-sdk](https://github.com/aws/sagemaker-python-sdk). The front-end custom MPI flag support require changes in [sagemaker-python-sdk](https://github.com/aws/sagemaker-python-sdk) and backend feature processing require changes in [sagemaker-training-toolkit](https://github.com/aws/sagemaker-training-toolkit). For user to use this feature, both the repository changes has to be present in the production. But to make things easier with respect to merging the code changes and availability of those features in production, we will divide this feature into two phases. The first phase is to make changes in [sagemaker-training-toolkit](https://github.com/aws/sagemaker-training-toolkit) which is PR [#99](https://github.com/aws/sagemaker-training-toolkit/pull/99) and this will merge first and be available in production via a DLC. This PR [#99](https://github.com/aws/sagemaker-training-toolkit/pull/99) will not break the existing feature, meaning, user can still run the SageMaker Distributed Data Parallel without custom MPI support. The second phase is to merge the changes in [sagemaker-python-sdk](https://github.com/aws/sagemaker-python-sdk) which is PR [#2255](https://github.com/aws/sagemaker-python-sdk/pull/2255). The integration test present in [sagemaker-python-sdk](https://github.com/aws/sagemaker-python-sdk) depends on the availability of feature [#99](https://github.com/aws/sagemaker-training-toolkit/pull/99) in production. The [sagemaker-python-sdk](https://github.com/aws/sagemaker-python-sdk) pypi wheel will be updated in DLC and Sagemaker Jupyter notebook conda environments. Once the PR [#99](https://github.com/aws/sagemaker-training-toolkit/pull/99) and PR [#2255](https://github.com/aws/sagemaker-python-sdk/pull/2255) available in production, user can use the custom mpi options in SageMaker Distributed Data Parallel.

*Testing done:*
- Ran the unit test
- Ran the SageMaker Distributed Data Parallel training on 2 node for TF2/PT

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-training-toolkit/blob/master/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-training-toolkit/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have used the regional endpoint when creating S3 and/or STS clients (if appropriate)
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-training-toolkit/blob/master/README.md)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ChaiBapchya — COMMENTED** [review]
Can you add another test where we set NCCL_DEBUG to some other accepted value?
`WARN` or `VERSION`. [1]
This is to confirm argument override works. From what I last remember, the override args didn't work as expected. 

[1] https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-debug

**Comment by ChaiBapchya** [comment]
Also for the CI failure-
It's failing at
```
tox -e flake8,black-check,pylint --parallel all
```
Specifically - black-check

To make it black compliant run
```
tox -e black-format
```
This will modify the codebase to make it black-check compliant.

**Comment by karan6181** [comment]
> You'd have to update the unit test SMDataparallelRunner call with the required positional arg `custom_mpi_options`
> 
> Similar to
> 
> https://github.com/aws/sagemaker-training-toolkit/blob/20815e47c54a41d883b060639eee119d34a00e61/test/unit/test_mpi.py#L111

Correct, I saw the failed build log and it requires the `custom_mpi_options`.

**Comment by karan6181** [comment]
- Ran the SageMaker Distributed Data Parallel MNIST training on 2 node for TF2/PT. Attached is the zip file containing jupyter notebook examples with output. Please open in any browser to view it. 
- Based on current available functionality, this PR doesn't have any breaking changes.
[SMDDP_MNIST_TRAINING.zip](https://github.com/aws/sagemaker-training-toolkit/files/6231819/SMDDP_MNIST_TRAINING.zip)

**Review by ChaiBapchya — APPROVED** [review]
Thanks! LGTM!

**Review by spidyDev — APPROVED** [review]

**Pull request merged**
