### PR TITLE
fix: SMDDP does not support P5 instances with SMP

### PR DESCRIPTION
**Pull request by apoorvtintin**
*Issue #, if available:*

*Description of changes:*
SMDDP collectives are unsupported in P5 instance types, this change aims to not allow usage of SMDDP collectives with SMP training framework on P5 instances.

*Testing done:*
Unit tests on smddpmprun pass on DLC PT2.0.1
before change
================ 3 failed, 282 passed, 2 skipped, 1 xfailed, 2 xpassed, 10 warnings, 2 error in 532.36 seconds ================
after change
================ 3 failed, 282 passed, 2 skipped, 1 xfailed, 2 xpassed, 10 warnings, 2 error in 532.36 seconds ================

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [X] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-training-toolkit/blob/master/CONTRIBUTING.md) doc
- [X] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-training-toolkit/blob/master/CONTRIBUTING.md#committing-your-change)
- [x] I have used the regional endpoint when creating S3 and/or STS clients (if appropriate)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-training-toolkit/blob/master/README.md)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by emeraldbay — COMMENTED** [review]
When SMDDP plan to add P5 support?

**Comment by apoorvtintin** [comment]
@emeraldbay Due to significant changes in hardware P5 support would be added some time later in the future

**Review by dhyeyp44 — APPROVED** [review]

**Review by emeraldbay — APPROVED** [review]
LGTM

**Comment by emeraldbay** [comment]
Please fix format through tox -e flake8,black-check,pylint

**Review by emeraldbay — APPROVED** [review]
LGTM

**Pull request closed without merging**
